### ISSUE TITLE
Expose `vertexId`

### ISSUE THREAD

**Issue by benjaminselfridge** [travitch/haggle#10]
From the haddocks:

> Furthermore, the types of vertices (nodes in FGL) and edges are held as abstract in haggle, allowing for changes later if necessary. That said, changes are unlikely and the representations are exposed (with no guarantees) through an Internal module.

However, I see no such internal module. I really just want the `vertexId` function so I can convert haggle graphs to fgl (thence to graphviz). But right now I don't see any way to do this. Am I missing something?

**Comment by travitch** [comment]
I've been chewing on how to design this for a while. The other feature blocked on this is usable to/from list functions.

I suppose there is no downside to exposing `Vertex -> Int`. It is still safe as long as there isn't `Int -> Vertex` (though there is still the danger of mixing `Vertex` values from different graphs).

**Comment by benjaminselfridge** [comment]
Would you consider just exposing the `Internal.Basic` module with a warning at the top of the module docs saying "IF YOU USE THIS WRONG YOU WILL MESS THINGS UP"???

**Comment by travitch** [comment]
Yeah I'm open to solving this either properly or temporarily. For the graphviz case in particular, is it possible to use `graphElemsToDot` (https://hackage.haskell.org/package/graphviz-2999.20.1.0/docs/Data-GraphViz.html#v:graphElemsToDot) directly, rather than going through fgl? I thought I'd done that before, and that function only requires `Ord n`, which should permit you to just use a `Vertex` directly.

**Comment by benjaminselfridge** [comment]
Ah, that might work! Thanks, I hadn't seen that one.

**Comment by travitch** [comment]
Fixed in #12
